POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "hamid",
    "password" : "hamid"
}
###
GET http://localhost:3000/getUser

###
POST http://localhost:3000/addExpence
Content-Type: application/json
Authorization: 7c92ec59-9649-4f8e-ba38-bcac1ebd0fc9

{
    "expencerUserID": "7c92ec59-9649-4f8e-ba38-bcac1ebd0fc9",
    "groupQuantity": "number",
    "title": "shomal",
    //"description": "string",
    "groupUserIds": 
[ {
    "id": "6228448c-7ccb-44a5-819c-192d64cce16c"
  },
  {
    "id": "43ec4408-f4ac-47be-802c-e7d5e534992f"
  },
  {
    "id": "6c1f0fb8-0e2d-43db-9db3-b9bca13d692f"
  }]
}
